name: Deploy Static Web to GitHub Pages

on:
  push:
    branches:
      - main

# กำหนดสิทธิ์ให้ GitHub Actions สามารถเข้ามาแก้ไขและอัปโหลดไฟล์เว็บได้
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.' # อัปโหลดไฟล์ทั้งหมดในโฟลเดอร์ปัจจุบัน

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4